url: https://tschopp.org
baseurl: https://tschopp.org

# Site settings
title: Tschopp Collective
email: ted@tschopp.org
description: "Tschopp.org is the official site of the Tschopp organization—sharing insights, ventures, and values across technology, leadership, and creative storytelling."


# Team names, titles and social links
people:
- name: Theodore Joseph Tschopp
  pic: Adult-Ted
  position: Lineage Architect & Storyteller-in-Residence
  social:
    - title: brands fa-mastodon
      url: https://twit.social/@TedT
    - title: brands fa-linkedin-in
      url: https://www.linkedin.com/in/tedtschopp
    - title: solid fa-house
      url: https://www.tedt.org/

- name: Louellen Marie Tschopp
  pic: Adult-Louellen
  position: Chief Financial Steward
  social:
    - title: facebook
      url: https://www.facebook.com/louellen.tschopp/
    - title: linkedin
      url: #

- name: Pieter William Conijn Tschopp
  pic: Adult-Pieter
  position: Engineer, Mobility & Machines
  social:
    - title: solid fa-house
      url: https://pieter.tschopp.org/

- name: Hannah Tschopp
  pic: Adult-Hannah
  position: Director of Operations & Optimism
  social:

      
- name: Helena Tschopp
  pic: Adult-Helena
  position: Steward of Smiles & Paws
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: solid fa-house
    url: http://tschopp.org
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Bradbury, CA 91010 

# Build settings
markdown: kramdown
permalink: pretty
