url: https://tschopp.org
baseurl: 

# Site settings
title: Tschopp
email: ted@tschopp.org
description: "Tschopp.org is the official site of the Tschopp organization—sharing insights, ventures, and values across technology, leadership, and creative storytelling."


# Team names, titles and social links
people:
- name: Theodore Joseph Tschopp
  pic: 1
  position: Founder & Storyteller-in-Residence
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Louellen Marie Tschopp
  pic: 2
  position: Chief Financial Steward
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Pieter William Conijn Tschopp
  pic: 3
  position: Engineer, Mobility & Machines
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Hannah Tschopp
  pic: 3
  position: Director of Operations & Optimism
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Helena Tschopp
  pic: 3
  position: Steward of Smiles & Paws
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
